# Generated by Django 3.0.7 on 2020-06-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='权限名字')),
                ('description', models.CharField(max_length=64, verbose_name='权限描述')),
            ],
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='VIP名字')),
                ('level', models.IntegerField(verbose_name='VIP等级')),
            ],
        ),
        migrations.CreateModel(
            name='VipPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_id', models.IntegerField(verbose_name='Vip ID')),
                ('permission_id', models.IntegerField(verbose_name='权限 ID')),
            ],
        ),
    ]
