# Generated by Django 3.0.7 on 2020-06-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='权限名字'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='level',
            field=models.IntegerField(unique=True, verbose_name='VIP等级'),
        ),
        migrations.AlterField(
            model_name='vip',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='VIP名字'),
        ),
    ]
