# Generated by Django 2.2 on 2020-06-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_id', models.IntegerField(verbose_name='用户1')),
                ('user2_id', models.IntegerField(verbose_name='用户2')),
            ],
        ),
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户')),
                ('stranger_id', models.IntegerField(verbose_name='陌生人')),
                ('create_datetime', models.DateTimeField(verbose_name='相识日期')),
                ('flag', models.CharField(choices=[('like', '喜欢'), ('superlike', '超级喜欢'), ('dislike', '不喜欢')], max_length=32)),
            ],
        ),
    ]
