# Generated by Django 3.0.7 on 2020-06-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiper',
            name='create_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='相识日期'),
        ),
    ]
