# Generated by Django 2.2 on 2020-05-28 12:22

from django.db import migrations, models
import lib.base_model


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200528_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='傻帽的名字')),
                ('user_id', models.IntegerField(verbose_name='用户的ID')),
            ],
            bases=(models.Model, lib.base_model.MixinModel),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
