# Generated by Django 2.2 on 2020-05-28 12:24

from django.db import migrations, models
import lib.base_model


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200528_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32, verbose_name='目标城市')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最小查找范围')),
                ('max_distance', models.IntegerField(default=10, verbose_name='最大查找范围')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最小交友年龄')),
                ('max_dating_age', models.IntegerField(default=99, verbose_name='最大交友年龄')),
                ('dating_sex', models.CharField(choices=[('男性', '男性'), ('女性', '女性')], max_length=16, verbose_name='交友性别')),
                ('vibration', models.BooleanField(default=True, verbose_name='是否开启震动')),
                ('only_matched', models.BooleanField(default=True, verbose_name='是否为匹配的人看我的相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='自动播放视频')),
            ],
            bases=(models.Model, lib.base_model.MixinModel),
        ),
    ]
