# Generated by Django 2.2 on 2020-05-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Other',
        ),
    ]
